// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Activate(arg1) {
  return window['go']['main']['App']['Activate'](arg1);
}

export function CheckActivation() {
  return window['go']['main']['App']['CheckActivation']();
}

export function DownloadBook(arg1, arg2) {
  return window['go']['main']['App']['DownloadBook'](arg1, arg2);
}

export function GetBookInfo(arg1) {
  return window['go']['main']['App']['GetBookInfo'](arg1);
}

export function GetTrending() {
  return window['go']['main']['App']['GetTrending']();
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
