// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Activate(arg1) {
  return window['go']['main']['App']['Activate'](arg1);
}

export function CheckActivation() {
  return window['go']['main']['App']['CheckActivation']();
}

export function DownloadAgg(arg1, arg2) {
  return window['go']['main']['App']['DownloadAgg'](arg1, arg2);
}

export function DownloadBook(arg1, arg2) {
  return window['go']['main']['App']['DownloadBook'](arg1, arg2);
}

export function DownloadFeilu(arg1, arg2) {
  return window['go']['main']['App']['DownloadFeilu'](arg1, arg2);
}

export function DownloadQidianHybrid(arg1, arg2) {
  return window['go']['main']['App']['DownloadQidianHybrid'](arg1, arg2);
}

export function GetBookInfo(arg1) {
  return window['go']['main']['App']['GetBookInfo'](arg1);
}

export function GetFeiluInfo(arg1) {
  return window['go']['main']['App']['GetFeiluInfo'](arg1);
}

export function GetQidianInfo(arg1) {
  return window['go']['main']['App']['GetQidianInfo'](arg1);
}

export function GetTrending() {
  return window['go']['main']['App']['GetTrending']();
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SearchAgg(arg1) {
  return window['go']['main']['App']['SearchAgg'](arg1);
}

export function SearchFeilu(arg1) {
  return window['go']['main']['App']['SearchFeilu'](arg1);
}

export function SearchQidian(arg1) {
  return window['go']['main']['App']['SearchQidian'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
