// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadBook(arg1:string,arg2:string):Promise<string>;

export function GetBookInfo(arg1:string):Promise<string>;

export function GetTrending():Promise<string>;

export function OpenDirectory(arg1:string):Promise<void>;

export function Search(arg1:string):Promise<string>;

export function SelectDirectory():Promise<string>;
