// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Activate(arg1:string):Promise<string>;

export function CheckActivation():Promise<string>;

export function DownloadAgg(arg1:string,arg2:string):Promise<string>;

export function DownloadBook(arg1:string,arg2:string):Promise<string>;

export function DownloadFeilu(arg1:string,arg2:string):Promise<string>;

export function DownloadQidianHybrid(arg1:string,arg2:string):Promise<string>;

export function GetBookInfo(arg1:string):Promise<string>;

export function GetFeiluInfo(arg1:string):Promise<string>;

export function GetQidianInfo(arg1:string):Promise<string>;

export function GetTrending():Promise<string>;

export function OpenDirectory(arg1:string):Promise<void>;

export function Search(arg1:string):Promise<string>;

export function SearchAgg(arg1:string):Promise<string>;

export function SearchFeilu(arg1:string):Promise<string>;

export function SearchQidian(arg1:string):Promise<string>;

export function SelectDirectory():Promise<string>;
